### ISSUE TITLE
Does not work in Safari with an element that has "position: absolute"

### ISSUE THREAD

**Issue by CKrawczyk** [nrako/react-component-resizable#13]
In Safari if you try to make an element with "position: absolute" resizable it does not work.  Dragging the resize handle only changes the size of the hidden contract-trigger div instead of the parent element (this gives the appearance that the resize handle does not work). 

The resize works as expected in Firefox, Chrome, and Opera.

**Comment by CKrawczyk** [comment]
I just found a workaround for this, changing the height of the resize-triggers class to 90% "uncovers" the resize handle of the base element making it clickable (I also tried moving the resize-triggers to a lower z-index, but that did not work).

**Comment by nrako** [comment]
@CKrawczyk is this still an open issue? If yes some minimal implementation of your issue that can be reproduced (in Safari?) would be great.

**Comment by CKrawczyk** [comment]
No, I got it working, just a css error on my part.

**Comment by nrako** [comment]
Cool, thank you for the feedback.
