### ISSUE TITLE
Sometimes see "this.refs.resizable is undefined" error in FF (looks like race condition)

### ISSUE THREAD

**Issue by pnuzhdin** [nrako/react-component-resizable#17]
It appears here:
https://github.com/nrako/react-component-resizable/blob/0.3.0/src/component.js#L79

I suppose it's the race condition.

**Comment by notthatnathan** [comment]
Seeing a related issue in Chrome.

```
Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
```
 at this line https://github.com/nrako/react-component-resizable/blob/1533802667e6c07aa8f5608394ffabf439df65d6/src/component.js#L81

Agree it seems like a race, happens inconsistently.
