### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by arcanis** [nrako/react-component-resizable#24]
The object spread syntax isn't currently standardized. Since [the last update](https://github.com/nrako/react-component-resizable/commit/92a0d37baec2192b0057edbd7414f801f42e888a#diff-d24fe73020f46dde060f58786e987b61R87), this module requires extra care when using it, because it won't work out of the box with webpack and server-side react rendering (even on modern ES6-compatible Node versions).

I think this change should be reverted, or the main entry point should be updated to use the `dist` build instead of the actual sources, at least until object spread is officially implemented in v8.

**Comment by nrako** [comment]
You're right @arcanis thanks. This shouldn't require a transpiler to work. I'm just gonna change the package.json to quickly target the dist build.

**Comment by arcanis** [comment]
Unfortunately, just using the dist build is not enough (it causes some issues with Webpack, which warns because the output file is partially minified). I've fixed the issue in my branch, [here](https://github.com/arcanis/react-component-resizable/tree/patch-1), I can open a PR if you like it.

**Comment by nrako** [comment]
Yeah I saw that, it's because browserify didn't bundled it as a UMD.

Thanks for the PR proposition but I'd like to keep the transpiling in place, specially if I have to keep maintaining this code. It's a quick fix and I'll push something soon hopefully, but now I took a ~~second~~ first look on the tests and they aren't really great so now I'm trying to quickly fix them.

**Comment by arcanis** [comment]
Any news ? :)

**Comment by zekedroid** [comment]
yup, waiting on this fix as well

**Comment by sverrejoh** [comment]
This is causing a lot of trouble. I wouldn't recommend expecting users to transform your source code manually. 

react-virtualized comes with an AutoSizer component doing the same job, which solves this issue for me.

**Comment by nrako** [comment]
Hi, I'm apologizing for this stalling issue. I made a new release under `1.1.0-rc1` through this PR #28 which should fix this issue. Please let me know if it doesn't.

This #28 PR should hopefully make it simpler and more enjoyable to contribute to this, for me first but also anyone else.
