### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by pkandathil** [nrako/react-component-resizable#30]
home/app/react/node_modules/react-component-resizable/src/component.js:87
react_1  |     const {triggersClass, expandClass, contractClass, embedCss, onResize, ...rest} = this.props;
react_1  |                                                                           ^^^
react_1  | SyntaxError: Unexpected token ...

**Comment by nrako** [comment]
@pkandathil could you try this branch and let me know how this turns out for you https://github.com/nrako/react-component-resizable/pull/28

That would be awesome, thanks
