### ISSUE TITLE
can't get it to work - minimal example code might help

### ISSUE THREAD

**Issue by barbalex** [nrako/react-component-resizable#8]
to me it is not clear, what is needed for a minimal implementation. In the provided example I don't understand which parts are needed and which might just be exemplary:

    <Resizable className="via transferPropsTo" onResize={this.onResize}>
     Content...
    </Resizable>

is 

    className="via transferPropsTo"

really needed? I would guess not.

Is

    onResize={this.onResize}

really needed? I would get yes but I get the following error with or without: "Uncaught TypeError: this.props.onResize is not a function"

Here is what I did:

1 import the component:

    import Resizable from 'react-component-resizable'

2 Include it's dom-function in a React render:

    <Resizable style={{width: 100 + 'px', height: 100 + 'px', backgroundColor: 'green'}}/>

or:

    <Resizable  onResize={this.onResize} style={{width: 100 + 'px', height: 100 + 'px', backgroundColor: 'green'}}/>

**Comment by nrako** [comment]
Well, sorry but there isn't much to explain, `className="via transferPropsTo"` is a quick way to says that this prop `className` as the others (i.e `style` in your example) get transferred down to the the child div but it's true that `transferPropsTo` was the [old react way of doing this](https://gist.github.com/sebmarkbage/a6e220b7097eb3c79ab7) but the [logic still applies](https://github.com/nrako/react-component-resizable/blob/master/src/component.js#L92). As of `onResize` yes it's required, this is why the `propTypes` definition are in the [readme](https://github.com/nrako/react-component-resizable#prop-types). 

I don't believe there is a need for a specific example more than there is already, moreover there is some basic tests. Above all this component is quite simple and follow most good common practices for react component, so I was hoping that the code would be self-explanatory if you are familiar with react component...? If I may... https://facebook.github.io/react/docs/reusable-components.html

If you find an issue within the code I'll be happy to help.

**Comment by cassus** [comment]
I agree with @barbalex . I'm trying to use this component and it's making me work hard for it: reading the tests, figuring out the params of `onResize`.
A minimal working example would help a lot!

**Comment by nrako** [comment]
I'll happily merge a PR, or if you can't have a working example just start a PR with what you have and I'll complete it. That would help me figure out what isn't clear enough. Thanks

**Comment by cassus** [comment]
I couldn't get this component to work and used a different solution.

**Comment by steve-taylor** [comment]
I don't know what isn't clear enough about the request for a minimal example.

**Comment by jayfunk** [comment]
Added an example in this pull request.
https://github.com/nrako/react-component-resizable/pull/9
